'use strict';
const titles={'1':'Lecture 1 · 水循环与水量平衡','2':'Lecture 2 · 湿度与降水形成','3':'Lecture 3 · 环流、降水与测量','4':'Lecture 4 · 雪与融雪','5':'扩展 · 蒸发与蒸散'};
const $=id=>document.getElementById(id);const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedAnswer=null;
let cardOrder=new Map();
let rangeStart=0,rangeEnd=Object.keys(titles).length-1;
function shuffleCards(){const ids=questions.map(q=>q.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}cardOrder=new Map(ids.map((id,i)=>[id,i]));}
let exam=[],notes={},view='home',questions=[],section='all',mode='learn',page=0,index=0,revealed=false,progress={};try{progress=JSON.parse(localStorage.getItem('ggr217-progress-v1')||'{}');if(!progress||Array.isArray(progress)||typeof progress!=='object')progress={}}catch{}
const tokenMap={'α':'\\alpha','β':'\\beta','φ':'\\varphi','ω':'\\omega','Ω':'\\Omega','Σ':'\\sum','Δ':'\\Delta','≥':'\\ge','≤':'\\le','≠':'\\ne','∞':'\\infty','∈':'\\in','→':'\\to'};
function tex(s){return s.replace(/([BSVFCPIXr])̃/g,'\\widetilde $1').replace(/[αβφωΩΣΔ≥≤≠∞∈→]/g,c=>tokenMap[c]).replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>'_'+String('₀₁₂₃₄₅₆₇₈₉'.indexOf(c))).replace(/−/g,'-').replace(/q\*/g,'q^*').replace(/E_([QP])/g,'\\mathbb E_$1').replace(/max\(/g,'\\max(').replace(/F_\(/g,'\\mathcal F_(').replace(/\bF_t\b/g,'\\mathcal F_t')}
function pretty(s){const chunks=s.split(/(\$[^$]+\$)/g);return chunks.map((part,i)=>i%2?esc(part):esc(part).replace(/(?:[BSVFCPIXr][₀₁₂₃₄₅₆₇₈₉](?:\(ω_[ud]\))?|[αβφωΩ](?:_[a-z0-9]+)?(?:\^i)?|q\*|[BSVFCPIXφ]_\w+(?:\^i)?)/g,t=>'$'+tex(t)+'$')).join('')}

function answerInline(s){return esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}
function answerMarkdown(s){const lines=s.split('\n');let html='',i=0;while(i<lines.length){if(!lines[i].trim()){i++;continue}if(lines[i].trim()==='\\['){const formula=[];i++;while(i<lines.length&&lines[i].trim()!=='\\]')formula.push(lines[i++]);i++;html+='<div class="math-scroll">\\['+esc(formula.join('\n'))+'\\]</div>';continue}if(lines[i].trim().startsWith('|')){const rows=[];while(i<lines.length&&lines[i].trim().startsWith('|')){const cells=lines[i++].trim().slice(1,-1).split('|').map(c=>c.trim());if(cells.every(c=>/^:?-+:?$/.test(c)))continue;rows.push(cells)}html+='<div class="math-scroll"><table class="exam-table"><thead><tr>'+rows.shift().map(c=>'<th>'+answerInline(c)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(c=>'<td>'+answerInline(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';continue}const p=[];while(i<lines.length&&lines[i].trim()&&!lines[i].trim().startsWith('|')&&lines[i].trim()!=='\\[')p.push(lines[i++]);html+='<p>'+answerInline(p.join('\n')).replace(/\n/g,'<br>')+'</p>'}return html}

function math(){if(window.renderMathInElement){renderMathInElement($('workspace'),{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false},{left:'\\[',right:'\\]',display:true},{left:'\\(',right:'\\)',display:false}],throwOnError:false,trust:false})}else if(!$('notice').textContent){$('notice').textContent='数学排版暂未加载；公式原文仍可阅读，请检查网络后刷新。'}}
function items(){const term=$('search').value.toLowerCase().trim(),filter=$('filter').value;const list=questions.filter(q=>{const p=progress[q.id];return(section==='all'||q.section===section)&&(mode!=='cards'||section!=='all'||Object.keys(titles).indexOf(q.section)>=rangeStart&&Object.keys(titles).indexOf(q.section)<=rangeEnd)&&(!term||(q.en+' '+q.zh+' '+q.explanation).toLowerCase().includes(term))&&(filter==='all'||filter==='new'&&!p||filter==='hard'&&p&&p.grade!=='easy'||filter==='due'&&(!p||p.due<=Date.now()))});return mode==='cards'?list.sort((a,b)=>(cardOrder.get(a.id)??0)-(cardOrder.get(b.id)??0)):list}
function save(){try{localStorage.setItem('ggr217-progress-v1',JSON.stringify(progress));return true}catch{$('notice').textContent='浏览器无法保存进度；本次仍可继续学习，请用“备份进度”保留记录。';return false}}
function rating(q){return `<div class="rating" role="group" aria-label="标记掌握程度"><button data-grade="hard" data-id="${q.id}">不会 · 10 分钟</button><button data-grade="medium" data-id="${q.id}">模糊 · 1 天</button><button data-grade="easy" data-id="${q.id}">会了 · 3 天</button></div>`}
function answer(q){return `<div class="answer"><span class="verdict ${q.answer?'':'false'}">${q.answer?'True · 对':'False · 错'}</span><div class="explanation math-scroll">${pretty(q.explanation)}</div>${q.note?`<div class="note">${esc(q.note)}</div>`:''}${mode!=='cards'||selectedAnswer!==null&&selectedAnswer!==q.answer?rating(q):''}</div>`}
function card(q,show){const p=progress[q.id];return `<article class="question ${mode==='cards'?'flash':''}"><div class="meta"><span class="tag">${q.id}</span><span>${titles[q.section]}</span>${q.supplementary?'<span class="tag">补充练习</span>':''}${p&&mode!=='cards'?`<span class="status">${{hard:'不会',medium:'模糊',easy:'会了'}[p.grade]||'已复习'}</span>`:''}</div><div class="en math-scroll" lang="en">${pretty(q.en)}</div><div class="zh math-scroll">${pretty(q.zh)}</div>${q.formula?'<div class="math-scroll">$$'+esc(q.formula)+'$$</div>':''}${mode==='cards'?`<div class="rating" role="group" aria-label="判断正误"><button data-choice="true" data-id="${q.id}" ${show?'disabled':''}>True · 对</button><button data-choice="false" data-id="${q.id}" ${show?'disabled':''}>False · 错</button></div>${show?`<p class="choice-result ${selectedAnswer===q.answer?'correct':'incorrect'}" role="status"><strong>${selectedAnswer===q.answer?'✓ 答对了':'✗ 答错了'}</strong><span>你选了 ${selectedAnswer?'True':'False'} · 正确答案：${q.answer?'True':'False'}</span></p>`+answer(q):''}`:show?answer(q):'<button class="reveal" data-reveal="'+q.id+'">'+(mode==='cards'?'翻面 · 查看答案':'查看答案与讲解')+'</button>'}</article>`}
function route(){const h=location.hash.slice(1)||'ggr217';view=h?'chapter':'home';if(h==='ggr217'){section='all';mode='notes'}if(h.startsWith('ggr217/')){const key=h.split('/')[1];if(titles[key]){view='chapter';section=key;mode='notes';}else{location.hash='ggr217';return}}reset()}
function draw(){
const isChapter=view==='chapter';const keys=Object.keys(titles);$('card-range').hidden=!(isChapter&&mode==='cards'&&section==='all');if(!$('card-range').hidden){$('card-range').innerHTML=`<h2>选择练习范围</h2><label>从 <output id="range-start-label">${keys[rangeStart]}</output><input id="range-start" aria-label="起始章节" type="range" min="0" max="${keys.length-1}" step="1" value="${rangeStart}"></label><label>到 <output id="range-end-label">${keys[rangeEnd]}</output><input id="range-end" aria-label="结束章节" type="range" min="0" max="${keys.length-1}" step="1" value="${rangeEnd}"></label><p>包含起止章节；调整后重新随机开始。</p>`}
document.querySelector('aside h2').textContent='GGR217';document.querySelector('.sub').textContent='水文学 · Hydrology';document.querySelector('.course-link').textContent='GGR217';document.querySelector('.brand').href='../';document.querySelector('.domain').href='../';document.querySelector('footer').innerHTML='TF卡片为考点改编练习；模拟题保留项目文档48题原文。进度保存在当前浏览器。<br>雪基础参考：<a href="https://nsidc.org/learn/parts-cryosphere/snow/science-snow" target="_blank" rel="noopener">NSIDC</a> · <a href="https://water.usgs.gov/nwaa-data/data-catalog/sector/water-quantity/model/wqn-ensemble-conus-nwaa-v1/variable/swe" target="_blank" rel="noopener">USGS SWE</a>';document.querySelector('aside').hidden=view==='home';document.querySelector('.layout').classList.toggle('library-home',view==='home');document.body.classList.toggle('home-view',view==='home');document.querySelector('.toolbar').hidden=!isChapter;$('notice').textContent='';$('stats').textContent='';$('page-title').textContent=view==='home'?'学习库':section==='all'?'GGR217':section+' '+titles[section];
$('sections').innerHTML='<button data-course>GGR217 · 全部内容</button>'+Object.keys(titles).map(k=>`<button data-section="${k}" class="${isChapter&&section===k?'active':''}">${k}　${titles[k]}</button>`).join('');
if(view==='home'){$('section-label').textContent='YOR1E · 学习库';$('workspace').innerHTML='<a class="minimal-course" href="#ggr217">GGR217</a>';return}
if(view==='course'){$('section-label').textContent='学习库 / GGR217';$('workspace').innerHTML=[['1','单期市场'],['2','利率与债券'],['3','多期市场']].map(([n,t])=>`<section class="chapter-group"><h2>第 ${n} 章 · ${t}</h2><div class="chapter-grid">${Object.keys(titles).filter(k=>k.startsWith(n+'.')).map(k=>`<a class="chapter-tile" href="#ggr217/${k}"><span class="tag">${k}</span><h3>${titles[k]}</h3><p>${(notes[k]||[]).length} 组知识点 · ${questions.filter(q=>q.section===k).length} 道题</p></a>`).join('')}</div></section>`).join('');return}
$('exam').classList.toggle('active',mode==='exam');$('notes').classList.toggle('active',mode==='notes');
if(mode==='exam'){$('learn').classList.remove('active');$('cards').classList.remove('active');$('filter').hidden=true;document.querySelector('.search').hidden=true;$('stats').textContent='48 道概念模拟题 · 中英文参考答案';$('workspace').innerHTML='<p class="notes-source">英文原题配上你提供的中英文参考答案。先独立作答，再展开核对；课件专属数值和图示描述以原PPT为准。</p>'+exam.map(q=>`<article class="question"><div class="meta"><span class="tag">Q${q.number}</span><span>${q.marks} marks · ${q.number>=25&&q.number<=32?'Long Answer':'Conceptual / Short Answer'}</span></div><div class="en">${pretty(q.en)}</div><details class="exam-answer"><summary>查看英文答案与中文讲解</summary><div class="answer"><h3>${answerInline(q.answerTitle||'参考答案')}</h3>${answerMarkdown(q.answer||'暂未加入答案')}</div></details></article>`).join('');math();return}

if(mode==='notes'){$('learn').classList.remove('active');$('cards').classList.remove('active');$('filter').hidden=true;document.querySelector('.search').hidden=true;$('section-label').textContent=section==='all'?'学习库 / GGR217':'GGR217 / '+section;$('stats').textContent='知识点';$('workspace').innerHTML='<p class="notes-source">依据GGR217项目讨论与48题文档整理。Lecture 4细节须核对原PPT；第5节为教材扩展。</p>'+(section==='all'?Object.keys(titles).flatMap(k=>[{title:k+' '+titles[k],body:'',chapterLink:k},...(notes[k]||[])]):(notes[section]||[])).map(n=>n.chapterLink?`<h2 class="notes-chapter"><a href="#ggr217/${n.chapterLink}">${esc(n.title)}</a></h2>`:`<article class="question knowledge"><h2>${esc(n.title)}</h2><div class="explanation math-scroll">${pretty(n.body)}</div></article>`).join('');math();return}
$('filter').hidden=false;document.querySelector('.search').hidden=false;
const list=items();$('section-label').textContent=section==='all'?'GGR217 · 全部章节':section+' · '+titles[section];$('stats').textContent=`${list.length} 道题 · ${questions.filter(q=>progress[q.id]).length} / ${questions.length} 已复习`;$('learn').classList.toggle('active',mode==='learn');$('cards').classList.toggle('active',mode==='cards');$('notice').textContent=false?'1.2 的历史评分为 9/10，剩余判错题未标明。以下答案按所贴课程模型解释，仍保留核对标记。':'';
if(!list.length){$('workspace').innerHTML='<div class="empty"><h2>这里暂时没有题目</h2><p>试试其他章节或筛选条件。</p></div>';return}
if(mode==='cards'){index=Math.min(index,list.length-1);$('workspace').innerHTML=`<div class="card-meta"><span>当前范围随机练习 · 选择 True 或 False 查看讲解。← 上一题 · → 下一题</span><span>${index+1} / ${list.length}</span></div>`+card(list[index],revealed)+`<div class="pagination"><button id="previous" ${index===0?'disabled':''}>上一张</button><button id="next" ${index===list.length-1?'disabled':''}>下一张</button></div>`}else{const pages=Math.ceil(list.length/10);page=Math.min(page,pages-1);$('workspace').innerHTML=list.slice(page*10,page*10+10).map(q=>card(q,false)).join('')+`<div class="pagination"><button id="previous" ${page===0?'disabled':''}>上一页</button><span>${page+1} / ${pages}</span><button id="next" ${page===pages-1?'disabled':''}>下一页</button></div>`}math()}
function reset(){page=0;index=0;revealed=false;selectedAnswer=null;draw()}
$('sections').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b){const next='ggr217/'+b.dataset.section;if(location.hash==='#'+next){mode='notes';reset()}else location.hash=next}else if(e.target.closest('[data-home]')){location.href='../'}else if(e.target.closest('[data-course]')){location.hash='ggr217'}});$('exam').onclick=()=>{mode='exam';reset()};$('notes').onclick=()=>{mode='notes';reset()};window.addEventListener('hashchange',route);$('learn').onclick=()=>{mode='learn';reset()};$('cards').onclick=()=>{mode='cards';$('search').value='';$('filter').value='all';shuffleCards();reset()};$('filter').onchange=reset;$('search').oninput=reset;
$('workspace').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.choice&&mode==='cards'){const q=items()[index];if(!q||q.id!==b.dataset.id||revealed)return;selectedAnswer=b.dataset.choice==='true';revealed=true;draw()}else if(b.dataset.reveal){const q=questions.find(q=>q.id===b.dataset.reveal);if(mode==='cards'){revealed=true;draw()}else{b.outerHTML=answer(q);math()}}else if(b.dataset.grade){const id=b.dataset.id;progress[id]={grade:b.dataset.grade,reviewed:Date.now(),due:Date.now()+({hard:600000,medium:86400000,easy:259200000}[b.dataset.grade])};save();if(mode==='cards'){const remaining=items();index=Math.min(index+($('filter').value==='all'?1:0),Math.max(0,remaining.length-1));revealed=false;selectedAnswer=null;draw()}else{const article=b.closest('article');let status=article.querySelector('.status');if(!status){status=document.createElement('span');status.className='status';article.querySelector('.meta').append(status)}status.textContent={hard:'不会',medium:'模糊',easy:'会了'}[b.dataset.grade];$('stats').textContent=`${items().length} 道题 · ${questions.filter(q=>progress[q.id]).length} / ${questions.length} 已复习`}}else if(b.id==='next'||b.id==='previous'){const delta=b.id==='next'?1:-1;if(mode==='cards'){index+=delta;revealed=false}else page+=delta;draw()}});
window.addEventListener('keydown',e=>{
if(view!=='chapter'||mode!=='cards'||!['ArrowLeft','ArrowRight'].includes(e.key)||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||e.isComposing)return;
if(e.target?.closest('input,textarea,select,[contenteditable]:not([contenteditable="false"]),[role="textbox"]'))return;
const list=items();if(!list.length)return;e.preventDefault();
const next=index+(e.key==='ArrowRight'?1:-1);if(next<0||next>=list.length)return;
index=next;revealed=false;selectedAnswer=null;draw();
});
$('card-range').addEventListener('input',e=>{if(e.target.id==='range-start'||e.target.id==='range-end')$(e.target.id+'-label').textContent=Object.keys(titles)[Number(e.target.value)]});
$('card-range').addEventListener('change',e=>{if(e.target.id==='range-start'){rangeStart=Number(e.target.value);rangeEnd=Math.max(rangeEnd,rangeStart)}else if(e.target.id==='range-end'){rangeEnd=Number(e.target.value);rangeStart=Math.min(rangeStart,rangeEnd)}else return;shuffleCards();reset()});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({course:'GGR217',exportedAt:new Date().toISOString(),progress},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ggr217-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
Promise.all(['questions.json','notes.json','exam.json'].map(url=>fetch(url+'?v=20261007-answers1').then(r=>{if(!r.ok)throw Error();return r.json()}))).then(([q,n,e])=>{questions=q;notes=n;exam=e;route();const ctx=document.modelContext;if(ctx?.registerTool){Promise.resolve(ctx.registerTool({name:'open_ggr217_question',description:'打开指定 GGR217 题目的记忆卡片。',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.id!=='string')throw Error('题号必须是字符串');const q=questions.find(q=>q.id===input.id);if(!q)throw Error('题号不存在');view='chapter';section=q.section;mode='cards';$('search').value='';$('filter').value='all';index=items().findIndex(x=>x.id===q.id);revealed=false;selectedAnswer=null;draw();return {id:q.id,answerVisible:false}}})).catch(()=>{})}}).catch(()=>{$('workspace').innerHTML='<div class="empty">题目加载失败，请刷新重试。</div>'});
